# This file is named config.conf instead of default.conf
# This is because nix will create an empty default.conf
[ids]
0001:0001          # Dell XPS Keyboard (AT Translated Set 2)
0000:0006:bdb72f48 # Video Bus to pass brightness keys to swhkd

[global]
# To ignore tap capslock to Esc if held more than 300 ms
overload_tap_timeout = 300
chord_timeout = 30

include capstohyper
include swapaltsuper
