#!/bin/bash

OPTIONS=$(cat <<-END
logout
restart
shutdown
END
)



res=$(rofi -dmenu -mesg "Whatsapp" <<< $OPTIONS)

if [ "$res" = "logout" ]; then
    i3-msg exit
fi
if [ "$res" = "restart" ]; then
    reboot
fi
if [ "$res" = "shutdown" ]; then
    poweroff
fi
exit 0
