# See https://nikitabobko.github.io/AeroSpace/guide#configuring-aerospace

# 1. CONFIGURABLES {{{

start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

default-root-container-layout = 'tiles' # tiles|accordion
default-root-container-orientation = 'auto' # horizontal|vertical|auto

# Mouse follows focus when focused app / monitor changes
on-focus-changed = ['move-mouse window-lazy-center']
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

automatically-unhide-macos-hidden-apps = true # Disable macOS "Hide application" (cmd-h) feature

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 10
    inner.vertical =   10
    outer.left =       10
    outer.bottom =     10
    outer.top =        10
    outer.right =      10
# }}}

# 'main' binding mode declaration
[mode.main.binding]
    # Refer to comment in default config for details about possible keys, modifiers and commands
    # https://github.com/nikitabobko/AeroSpace/blob/main/docs/config-examples/default-config.toml

    # 2. WORKSPACE NAVIGATION {{{

    ## Navigate // Relative Window // <⎇ > H J K L ##
    alt-h = 'focus left  --boundaries all-monitors-outer-frame'
    alt-j = 'focus down  --boundaries all-monitors-outer-frame'
    alt-k = 'focus up    --boundaries all-monitors-outer-frame'
    alt-l = 'focus right --boundaries all-monitors-outer-frame'
    alt-a = 'focus left  --boundaries all-monitors-outer-frame'
    alt-s = 'focus down  --boundaries all-monitors-outer-frame'
    alt-w = 'focus up    --boundaries all-monitors-outer-frame'
    alt-d = 'focus right --boundaries all-monitors-outer-frame'

    ## Navigate // Workspaces 1-10 // <⎇ > 0..9 ##
    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-7 = 'workspace 7'
    alt-8 = 'workspace 8'
    alt-9 = 'workspace 9'
    alt-0 = 'workspace 10'

    ## Navigate // Relative Workspace // <Hyper> D F ##
    cmd-ctrl-alt-d = "workspace prev"
    cmd-ctrl-alt-f = "workspace next"

    # }}}

    # 3. WORKSPACE MODIFICATION {{{

    ## Modify // Window Position // <⎇ > H J K L ##
    alt-shift-h = 'move left  --boundaries all-monitors-outer-frame'
    alt-shift-j = 'move down  --boundaries all-monitors-outer-frame'
    alt-shift-k = 'move up    --boundaries all-monitors-outer-frame'
    alt-shift-l = 'move right --boundaries all-monitors-outer-frame'
    alt-shift-a = 'move left  --boundaries all-monitors-outer-frame'
    alt-shift-s = 'move down  --boundaries all-monitors-outer-frame'
    alt-shift-w = 'move up    --boundaries all-monitors-outer-frame'
    alt-shift-d = 'move right --boundaries all-monitors-outer-frame'

    # Modify // Move active window to workspace 1-10 // <⎇ ><Shift> 0..9 ##
    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-6 = 'move-node-to-workspace 6'
    alt-shift-7 = 'move-node-to-workspace 7'
    alt-shift-8 = 'move-node-to-workspace 8'
    alt-shift-9 = 'move-node-to-workspace 9'
    alt-shift-0 = 'move-node-to-workspace 10'

    # }}}

    # 4. MORE WM BINDINGS {{{

    alt-enter = '''exec-and-forget open -na alacritty'''

    ## Modify // Window Fullscreen Toggle // <⎇ > F ##
    alt-f = 'fullscreen --no-outer-gaps'
    ## Modify // Window Floating Toggle // <⎇ ><Shift> F ##
    alt-shift-f = 'layout floating tiling'

    alt-tab = 'workspace-back-and-forth'
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'

    alt-slash = 'layout tiles horizontal vertical'
    alt-comma = 'layout accordion horizontal vertical'

    # }}}

    # 5. SCRATCHPADS {{{

    # aerospace-scratchpad is only available via Homebrew
    cmd-ctrl-alt-w = "exec-and-forget aerospace-scratchpad show SeaTalk"
    cmd-ctrl-alt-e = "exec-and-forget aerospace-scratchpad show Obsidian"

    # }}}

    # 6. HOTKEYS {{{
    # For bindings that are not WM-specific
    # (In linux we use swhkd for this purpose)

    ## Launch // Dotfiles Editor // <⎇ > O ##
    alt-o = 'exec-and-forget sh -c "TERMINAL=alacritty EDITOR=nvim ~/dotfiles/scripts/dotsman/dotsman.sh dmenu choose"'

    ## Launch // Print screen via Flameshot // <⎇ > P ##
    alt-p = 'exec-and-forget osascript ~/dotfiles/scripts/flameshot.scpt'

    # }}}

    alt-backtick = 'mode service'

# 'service' binding mode declaration
[mode.service.binding]
    esc = ['reload-config', '''exec-and-forget terminal-notifier -title Aerospace -message "Config reloaded!"''', 'mode main']
    r = ['flatten-workspace-tree', 'mode main'] # reset layout

    # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
    #s = ['layout sticky tiling', 'mode main']

    alt-shift-h = ['join-with left', 'mode main']
    alt-shift-j = ['join-with down', 'mode main']
    alt-shift-k = ['join-with up', 'mode main']
    alt-shift-l = ['join-with right', 'mode main']

[exec]
    inherit-env-vars = true

[exec.env-vars]
    # Add Nix and Homebrew to PATH
    PATH = '/run/current-system/sw/bin:${HOME}/.nix-profile/bin:/opt/homebrew/bin:/usr/bin:${PATH}'

