{ config, ... }: let
  # We source the bulk of the config so that changes can be made without a rebuild
  main-config-path = "$HOME/dotfiles/desktop/hypr/hyprland.conf";
  colors-config-path = "$HOME/dotfiles/desktop/hypr/colors.conf"; # Was autogenerated by nix
in {
  wayland.windowManager.hyprland = {
    # Enable configuring by home-manager, but program itself is made available by NixOS
    enable = true;
    settings = {
      source = [
        # Source colors first for variables to be available in main config
        colors-config-path
        main-config-path
      ];
      exec-once = [
        "hyprctl setcursor ${config.home.pointerCursor.name} ${toString config.home.pointerCursor.size}"
      ];
    };
  };
}
