{config, ...}: let
  # We source the bulk of the config so that changes can be made without a rebuild
  main-config-path = "$HOME/dotfiles/desktop/hypr/hyprland.conf";
  colors-config-path = "$HOME/dotfiles/desktop/hypr/colors.conf"; # Was autogenerated by nix
in {
  # Enable configuring by home-manager, but program itself is made available by NixOS
  # Don't use wayland.windowManager.hyprland module, otherwise hyprland version may be incompatible with newer NixOS
  # (e.g. crash bug when home profile accidentally not updated)
  wayland.windowManager.hyprland = {
    enable = true;
  };
  xdg.configFile."hypr/hyprland.conf" = {
    text = ''
      # This line is what wayland.windowManager.hyprland module would generate
      exec-once = dbus-update-activation-environment --systemd DISPLAY HYPRLAND_INSTANCE_SIGNATURE WAYLAND_DISPLAY XDG_CURRENT_DESKTOP && systemctl --user stop hyprland-session.target && systemctl --user start hyprland-session.target

      source=${colors-config-path}
      source=${main-config-path}
      exec-once=hyprctl setcursor ${config.home.pointerCursor.name} ${toString config.home.pointerCursor.size}
    '';
  };
}
